package application;

import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Button;

import javafx.scene.control.TextField;
import javafx.scene.input.KeyCode;

import java.net.URL;
import java.util.ResourceBundle;

import javax.net.ssl.SSLException;

import com.jfoenix.validation.RequiredFieldValidator;
import com.sun.glass.events.KeyEvent;
import com.sun.glass.ui.TouchInputSupport;

import javafx.application.Platform;
import javafx.event.ActionEvent;
import javafx.event.Event;
import javafx.scene.control.ProgressBar;

import javafx.scene.layout.AnchorPane;
import javafx.scene.paint.Color;
import javafx.scene.text.Text;
import javafx.scene.control.RadioButton;

import javafx.scene.control.PasswordField;

import javafx.scene.control.CheckBox;

public class homeController implements Initializable {
	@FXML
	private AnchorPane pan;
	@FXML
	private Button login;
	@FXML
	private RadioButton user_read;
	@FXML
	private RadioButton user_work;
	@FXML
	private CheckBox rememberInfo;
	@FXML
	private TextField user_id;
    @FXML
    private Text judeId;
	@FXML
	private PasswordField user_password;
    @FXML
    private Text judePassword;
	private int flag=0;//≈–∂œ—ß…˙orΩÃ ¶µ«¬º
	private innit myapp;
	private Basic base=new Basic();
	public void setapp(innit myapp) {
		this.myapp=myapp;
	}
	public void initialize(URL location, ResourceBundle resources) {
		// TODO Auto-generated method stub
		login.setOnKeyPressed(this::login_key);
		rememberInfo.setSelected(true);
		user_read.setSelected(true);flag=1;
		user_work.setSelected(false);	
	}
	 @FXML
	    void loginreader(ActionEvent event) {
		 if(user_read.isSelected())
				{user_work.setSelected(false);
				flag=1;
				}

	    }

	    @FXML
	    void loginwork(ActionEvent event) {
	    	if(user_work.isSelected())
				{user_read.setSelected(false);
				 flag=0;
				}

	    }

	// Event Listener on Button[#login].onAction
	@FXML
	public void login(ActionEvent event) {
		judeId.setText(null);
		judePassword.setText(null);
		// TODO Autogenerated
		if (user_id.getText().length()==0) {
			judeId.setText("«Î ‰»Î’ ∫≈");
			return;
		}
		if (user_password.getText().length()==0) {
			judePassword.setText("«Î ‰»Î√‹¬Î");
			return;
		}
		if(base.logindata(user_id.getText(),user_password.getText(),flag))
		{
			if (flag==1) {				
				myapp.toStu(base);
			}
			if(flag==0)
				{
					myapp.toAdmin(base);
				}
			
			
			/*myProgress myProgress=new myProgress(prgs_login);
			thread=new Thread(myProgress);
			prgs_login.setVisible(true);
			prgs_login.setProgress(0.5);*/
		}
		else {
			judeId.setText("”√ªßªÚ√‹¬Î¥ÌŒÛ");
			return;			
		}
		
	}
	public void login_key(javafx.scene.input.KeyEvent e) {
		if(e.getCode()==KeyCode.ENTER){
            user_id.setText("hello");
        }
	}


}

